#!/usr/bin/env node
/**
 * Reads static asset files in src/assets/ and emits src/assets.ts with one
 * exported string constant per file. Keeps the runtime portable across Node,
 * Vercel functions and Cloudflare Workers/Pages (no filesystem access at
 * request time — everything is inlined at build time).
 *
 * Source files → exported constants:
 *   src/assets/home.html    → INDEX_HTML
 *   src/assets/privacy.html → PRIVACY_HTML
 *   src/assets/favicon.svg  → FAVICON_SVG
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const sources = [
  { file: "src/assets/home.html", name: "INDEX_HTML" },
  { file: "src/assets/privacy.html", name: "PRIVACY_HTML" },
  { file: "src/assets/favicon.svg", name: "FAVICON_SVG" },
];

const escape = (raw) =>
  raw.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const blocks = sources.map(({ file, name }) => {
  const raw = readFileSync(resolve(root, file), "utf8");
  return `export const ${name} = \`${escape(raw)}\`;\n`;
});

const out =
  `// AUTO-GENERATED by scripts/build-assets.mjs — do not edit by hand.\n` +
  `// Edit the source files in src/assets/ instead, then run \`npm run assets\`.\n` +
  `//\n` +
  `// Inlined as strings so the same module works across Node, Vercel functions\n` +
  `// and Cloudflare Workers/Pages without filesystem access at request time.\n\n` +
  blocks.join("\n");

writeFileSync(resolve(root, "src/assets.ts"), out);
console.log(`assets: wrote src/assets.ts (${sources.length} files)`);
