#!/usr/bin/env node
/**
 * Reads static asset files in src/assets/ and emits src/assets.ts with one
 * exported constant per file. Keeps the runtime portable across Node, Vercel
 * functions and Cloudflare Workers/Pages (no filesystem access at request
 * time — everything is inlined at build time).
 *
 * Text files (html/svg) are inlined as template-literal strings.
 * Binary files (png/jpg) are inlined as base64 strings, decoded once at module
 * load time into a Uint8Array (works in both Node and Workers runtimes).
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = dirname(here);

const sources = [
  { file: "src/assets/home.html", name: "INDEX_HTML", kind: "text" },
  { file: "src/assets/privacy.html", name: "PRIVACY_HTML", kind: "text" },
  { file: "src/assets/favicon.svg", name: "FAVICON_SVG", kind: "text" },
  { file: "src/assets/og.png", name: "OG_PNG", kind: "binary" },
];

const escape = (raw) =>
  raw.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const blocks = sources.map(({ file, name, kind }) => {
  const buf = readFileSync(resolve(root, file));
  if (kind === "text") {
    return `export const ${name} = \`${escape(buf.toString("utf8"))}\`;\n`;
  }
  return `export const ${name} = base64ToBytes("${buf.toString("base64")}");\n`;
});

const helper = `function base64ToBytes(b64: string): Uint8Array {
  const decode: (s: string) => string =
    typeof atob === "function"
      ? atob
      : (s) => globalThis.Buffer.from(s, "base64").toString("binary");
  const bin = decode(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
`;

const out =
  `// AUTO-GENERATED by scripts/build-assets.mjs — do not edit by hand.\n` +
  `// Edit the source files in src/assets/ instead, then run \`npm run assets\`.\n` +
  `//\n` +
  `// Inlined at build time so the same module works across Node, Vercel\n` +
  `// functions and Cloudflare Workers/Pages without filesystem access.\n\n` +
  helper +
  `\n` +
  blocks.join("\n");

writeFileSync(resolve(root, "src/assets.ts"), out);
console.log(`assets: wrote src/assets.ts (${sources.length} files)`);
